# Generated by Django 5.0.3 on 2024-04-17 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_name', models.CharField(help_text='The name of the service.', max_length=200, unique=True)),
                ('is_service_active', models.BooleanField(default=True, help_text='Indicates if the service is active or not.')),
                ('user', models.ForeignKey(help_text='The user associated with the service.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserApiInteractionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_prompt', models.TextField(help_text='The prompt or input from the user.')),
                ('api_output', models.TextField(help_text='The output or response from the API.')),
                ('api_service', models.ForeignKey(help_text='The associated service from the Service model.', on_delete=django.db.models.deletion.CASCADE, to='figma.service')),
                ('user', models.ForeignKey(help_text='The user associated with the interaction.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
