# Generated by Django 5.0.3 on 2024-04-17 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_submitted', 'Not Submitted'), ('in_review', 'In Review'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='in_review', max_length=100)),
                ('file_key', models.CharField(blank=True, max_length=200, null=True)),
                ('file_path_prefix', models.CharField(blank=True, max_length=200, null=True)),
                ('file_path', models.CharField(blank=True, max_length=200, null=True)),
                ('url', models.URLField()),
                ('document_type', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Files',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_id', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_image', to='core.userfile')),
            ],
            options={
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
